create extension if not exists pgcrypto;

create table public.festivals (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 80),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  pin_hash text not null,
  created_at timestamptz not null default now()
);

create table public.festival_members (
  festival_id uuid not null references public.festivals(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (festival_id, user_id)
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  festival_id uuid not null references public.festivals(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  unique (festival_id, name)
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  festival_id uuid not null references public.festivals(id) on delete cascade,
  name text not null,
  price numeric(10,2) not null check (price >= 0),
  category text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  festival_id uuid not null references public.festivals(id) on delete cascade,
  table_number text not null,
  notes text not null default '',
  total numeric(10,2) not null check (total >= 0),
  paid boolean not null default false,
  kitchen_done boolean not null default false,
  bar_done boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  festival_id uuid not null references public.festivals(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  name text not null,
  price numeric(10,2) not null,
  quantity integer not null check (quantity > 0),
  category text not null
);

create index categories_festival_idx on public.categories(festival_id);
create index products_festival_idx on public.products(festival_id);
create index orders_festival_created_idx on public.orders(festival_id, created_at desc);
create index order_items_festival_idx on public.order_items(festival_id);

alter table public.festivals enable row level security;
alter table public.festival_members enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create function public.is_festival_member(target_festival uuid)
returns boolean language sql stable security invoker set search_path = '' as $$
  select exists (select 1 from public.festival_members where festival_id = target_festival and user_id = auth.uid());
$$;

create policy "members read festivals" on public.festivals for select to authenticated using (public.is_festival_member(id));
create policy "members read membership" on public.festival_members for select to authenticated using (user_id = auth.uid());

do $$ declare table_name text; begin
  foreach table_name in array array['categories','products','orders','order_items'] loop
    execute format('create policy "members read %1$s" on public.%1$I for select to authenticated using (public.is_festival_member(festival_id))', table_name);
    execute format('create policy "members insert %1$s" on public.%1$I for insert to authenticated with check (public.is_festival_member(festival_id))', table_name);
    execute format('create policy "members update %1$s" on public.%1$I for update to authenticated using (public.is_festival_member(festival_id)) with check (public.is_festival_member(festival_id))', table_name);
    execute format('create policy "members delete %1$s" on public.%1$I for delete to authenticated using (public.is_festival_member(festival_id))', table_name);
  end loop;
end $$;

create or replace function public.register_festival(p_name text, p_slug text, p_pin text)
returns public.festivals
language plpgsql security definer set search_path = '' as $$
declare created public.festivals;
begin
  if auth.uid() is null or char_length(p_pin) < 4 then raise exception 'invalid registration'; end if;
  insert into public.festivals(name, slug, pin_hash)
  values (trim(p_name), lower(trim(p_slug)), crypt(p_pin, gen_salt('bf'))) returning * into created;
  insert into public.festival_members(festival_id, user_id) values (created.id, auth.uid());
  insert into public.categories(festival_id, name, sort_order) values (created.id, 'Cucina', 0), (created.id, 'Bere', 1);
  return created;
end $$;

create or replace function public.login_festival(p_slug text, p_pin text)
returns public.festivals
language plpgsql security definer set search_path = '' as $$
declare found public.festivals;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  select * into found from public.festivals where slug = lower(trim(p_slug)) and pin_hash = crypt(p_pin, pin_hash);
  if found.id is null then raise exception 'invalid credentials'; end if;
  insert into public.festival_members(festival_id, user_id) values (found.id, auth.uid()) on conflict do nothing;
  return found;
end $$;

revoke all on function public.register_festival(text, text, text) from public, anon;
revoke all on function public.login_festival(text, text) from public, anon;
grant execute on function public.register_festival(text, text, text) to authenticated;
grant execute on function public.login_festival(text, text) to authenticated;
grant select, insert, update, delete on public.categories, public.products, public.orders, public.order_items to authenticated;
grant select on public.festivals, public.festival_members to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter publication supabase_realtime add table public.orders, public.order_items, public.categories, public.products;
